services:
  service-main:
    build:
      context: ./service.main
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - service-network
  service-notification:
    build:
      context: ./service.notification
    ports:
      - "8082:8082"
    depends_on:
      service-main:
        condition: service_healthy
    networks:
      - service-network
  service-tasks:
    build:
      context: ./service.one
    ports:
      - "8081:8081"
    depends_on:
      service-main:
        condition: service_healthy
      service-notification:
        condition: service_started
    networks:
      - service-network
networks:
  service-network:
    driver: bridge